#print("exercicios aula de python")
#print(" 1 CALCULAR O QUADRADO")
#a = int(input("Digite um numero: "))
#b = a*a
#print("o quadrado desse valor é ",b)
##print("2 Programa, informar tres numeros inteiros")
#ah = int(input("Digite o primeiro valor: "))
#be = int(input("Digite o segundo valor: "))
#ce = int(input("Digite o terceiro valor: "))
#a1 = ah ** 2S
#b1 = be ** 2
#c1 = ce ** 2
#result = (a1 + b1 + c1)
#print("O resultado é: ",result)
##print(" 3 programa, usuario informa quatro valores, o programa mostra o resultado")
#va1 = int(input("Digite o primeiro valor: "))
#va2 = int(input("Digite o segundo valor: "))
#va3 = int(input("Digite o terceiro valor: "))
#va4 = int(input("Digite o terceiro valor: ")))
#resultvalue = ((va1*va3) + (va2+va4))
#print("Soma geral é de: ", resultvalue)
#resultvalues1 = (va1*va3)
#resultvalues2 = (va2+va4)
#print("\n Multiplicação do primeiro com o terceiro é: ", resultvalues1)
#print("\n Soma soma do segundo com o quarto é: ",resultvalues2)
##print("Programa de cotação")
#dolar = float(input("Digite o valor do Dolar: "))
#reais = (dolar) * 4.48
#print("O valor em reais é: ",reais)
##print("Programa abastecimento")
#valuedinheiro = float(input("Quer abastecer quantos litros: "))
#litros = (valuedinheiro)/4.30
#print("Voce colocou: ", valuedinheiro," Reais em gasolina")
#print("Você colocou: ", round((valuedinheiro)/4.30, 2),"Litros de gasolina")
##print("Programa de Temperatura")
#tc = int(input("Digite a temperatura em Célsius: "))
#tf = ((9*tc)+160)/5
#print("A temperatura em Fahrenheit é: ",tf)
##print("Programa Volume")
#altura = int(input("Digite a altura do recipiente: "))
#raio = int(input("Digite o raio: "))
#volume = (3.14*(raio ** 2)*altura)
#print("O Volume é igual: ", round(volume, 2))
##print("Programa prestação")
#boleto = int(input("Informe o valor do boleto: "))
#juros = int(input("Digite Quanto de juros de 0a100: "))
#jurosporcentual = (juros/100)
#dias = int(input("Digite os Dias de atraso: "))
#novo_valor = boleto + (boleto*(jurosporcentual)*dias)
#print("O novo boleto a ser pago é de R$",novo_valor,"Reais, com juros:",juros,"% por", dias,"dias")
##print("Programa milionario")
#renda = int(input("Digite sua renda mensal: "))
#dispesa = int(input("Digite suas despesas mensais: "))
#rentavel = (renda-dispesa)
#rentavelanual = (rentavel*12)
#print("Sua renda é de ",renda,"abaixo sua renda em 6 meses")
#print("1 mes",rentavel, "2 meses",rentavel*2,"3 meses",rentavel*3)
#print("4 meses",rentavel*4, "5 meses",rentavel*5,"6 meses",rentavel*6)
#print("Em um ano você teria",rentavel*12,"Reais")
#print("Em 2 anos você teria",rentavelanual*2,"Reais")
#print("Em 3 anos você teria",rentavelanual*3,"Reais")
#print("Em 4 anos você teria",rentavelanual*4,"Reais")
#print("Em 5 anos você teria",rentavelanual*5,"Reais")
#print("Em 6 anos você teria",rentavelanual*6,"Reais")
#print("Em 7 anos você teria",rentavelanual*7,"Reais")
#print("Para ser considerado rico você precisa ganhar 700 mil por ano")
#print("Para ser rico precisa economizar: ",(round(700000 - rentavelanual))," em um ano")
#print("Precisa economizar: ",round((700000 - rentavelanual)/12),"Por mês")
#print("Sua deveria ser: ", round(rentavel + (700000 - rentavelanual)/12),"por Mes")
